# Generated by Django 2.1.3 on 2018-11-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.SlugField(blank=True, max_length=32, unique=True, verbose_name='Réf.')),
                ('building', models.CharField(choices=[('CHAUD', 'Les Chaudannes'), ('BUFF', 'La Buffaz'), ('AND', 'Andagne')], max_length=16, verbose_name='Bâtiment')),
                ('number', models.IntegerField(verbose_name='Numéro')),
                ('description', models.TextField(verbose_name='Description')),
                ('isOpen', models.BooleanField(default=True, verbose_name='Réservable')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Réf.')),
                ('startDate', models.DateField(verbose_name='Date début séjour')),
                ('endDate', models.DateField(verbose_name='Date fin séjour')),
                ('price', models.FloatField(verbose_name='Prix location')),
                ('totalPrice', models.FloatField(verbose_name='Prix total du séjour')),
                ('firmed', models.BooleanField(default=False, verbose_name='Contrat signé ?')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('M. ou Mme', 'Monsieur ou Madame')], max_length=16, verbose_name='Civilité')),
                ('firstname', models.CharField(max_length=64, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=64, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=16, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postalCode', models.IntegerField(verbose_name='Code postal')),
                ('city', models.CharField(max_length=64, verbose_name='Ville')),
                ('country', models.CharField(default='FRANCE', max_length=64, verbose_name='Pays')),
                ('reminder', models.TextField(blank=True, verbose_name='Pense bête')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Prix option')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='options',
            field=models.ManyToManyField(to='gestion.Option'),
        ),
    ]
