# Generated by Django 2.1.3 on 2018-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Capacité'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Etage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='numRooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de pièces'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Numéro'),
        ),
    ]
